---
# handlers file for elabftw_install
- name: clear_cache
  command: rm -rf twig/*
  args:
    chdir: /var/www/html/elabftw/cache
    warn: false

- name: webserver_start
  service:
    name: apache2
    state: started

- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: restart php-fpm
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm.service"
    state: restarted
